### PR TITLE
Optionally show the file’s Type in the header-line.

### LINKED ISSUE #6: option to show Type of file in `header-line`
The type of the expression in a file can be captured with a command like
```bash
dhall --plain <<< $file 2>&1 >/dev/null
```
This can be used in `header-line-format` to always display the type at the top of the window.

It should also display a reasonable message when 1. there is an error or 2. the type is too large[†].

(I might do this myself, but wanted to open the issue as a reminder until I get to it.)

[†]: Maybe some day there will be a way to acquire a shorter type without it expanding all the aliases and imports along the way.

### PR DESCRIPTION
**Pull request by sellout**
Fixes #6.

screen shot 2018-04-04 at 13 13 28

### CODE REVIEW

**Comment by psibi** [comment]
Thanks!

**Comment by purcell** [comment]
This is neat, but it must require an extremely recent Dhall, no? Even Dhall from a late Feb Stackage nightly doesn't have the `--plain` option, so the header line just contains a "usage" error by default for me.

**Comment by sellout** [comment]
@purcell You’re right – this requires Dhall 1.11, which is what we use at work. The problem is that without `--plain` on 1.11, you get bash escapes in the string.

I should conditionalize the command based on the Dhall version (which I was planning to do anyway to take advantage of dhall-lang#352).

**Comment by purcell** [comment]
> The problem is that without --plain on 1.11, you get bash escapes in the string.

You could maybe just pass the string through one of the `ansi-color` functions.

**Comment by psibi** [comment]
Ah, I didn't foresee this. @sellout Would be glad to take another PR. If you are busy, I will see if I can fix it by tomorrow. Thanks!

**Comment by sellout** [comment]
Yeah, I should be able to submit something quickly using ansi-color.

Thanks for the suggestion @purcell, that’s a better solution.

**Pull request merged**
